version: '3'
services:
  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis

volumes:
  redis-data:

networks:
  redis:
    driver: bridge
