apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/service_type: backend
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/service_type: backend
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/service_type: backend
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "chart.fullname" . }}-backend-sa
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: OTEL_SERVICE_NAME
            value: {{ .Chart.Name }}
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "service.name={{ .Chart.Name }},service.version={{ .Chart.Version }}"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{ .Values.otel.collector.endpoint }}
          - name: TRACE_MODE
            value: {{ .Values.otel.enabled | ternary "prod" "dev" | quote }}
          - name: REDIS_URI
            {{- if .Values.redis.inClusterEnabled }}
            value: "{{ include "chart.fullname" . }}-redis.{{ .Release.Namespace }}.svc.cluster.local"
            {{- else }}
            value: {{ .Values.redis.host }}
            {{- end }}
          - name: REDIS_PORT
            value: {{ quote .Values.redis.port }}
          - name: BUCKET_NAME
            value: {{ .Values.gcsBucket.name }}
          - name: GCP_PROJECT_ID
            value: {{ .Values.firestore.projectId }}
          - name: FIRESTORE_DATABASE_ID
            value: {{ .Values.firestore.database }}
          - name: FIRESTORE_COLLECTION
            value: {{ .Values.firestore.collection }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/hck
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /api/v1/hck
              port: http
              scheme: HTTP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
