{{- if .Values.gateway.enabled }}
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ include "chart.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  {{- with .Values.gateway.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            shared-gateway-access: "true"
    tls:
      mode: Terminate
      options:
        networking.gke.io/pre-shared-certs: {{ .Values.gateway.gcpCertName }}
  addresses:
  - type: NamedAddress
    value: {{ .Values.gateway.ipName }}
{{- end }}
