{{- if .Values.gateway.enabled }}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "chart.fullname" . }}-hck
  namespace: {{ .Release.Namespace }}
spec:
  default:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.service.targetPort }}
        requestPath: /api/v1/hck
        proxyHeader: NONE
  targetRef:
    group: ""
    kind: Service
    name: {{ include "chart.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
